# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  # config.vm.box_download_insecure = true
  # config.vm.define "shoppingmallClient" do |cfg|
  #   cfg.vm.box = "centos/7"
  #   cfg.vm.provider "virtualbox" do |vb|
  #     vb.name = "shoppingmall"
  #     vb.cpus = 1
  #     vb.memory = 1024
  #   end
  #   cfg.vm.host_name = "shoppingmallClient"
  #   cfg.vm.network "private_network", ip: "192.168.56.100"
  #   cfg.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true, id: "httpd"
  #   cfg.vm.provision "shell", path: "install.sh"
  # end

  # config.vm.define "shoppingmallBackOffice" do |cfg|
  #   cfg.vm.box = "centos/7"
  #   cfg.vm.provider "virtualbox" do |vb|
  #     vb.name = "shoppingmallBackOffice"
  #     vb.cpus = 1
  #     vb.memory = 1024
  #   end
  #   cfg.vm.host_name = "shoppingmallBackOffice"
  #   cfg.vm.network "private_network", ip: "192.168.56.101"
  #   cfg.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true, id: "httpd"
  #   cfg.vm.provision "shell", path: "install.sh"
  # end

  # config.vm.define "shoppingmallMariaDB" do |cfg|
  #   cfg.vm.box = "centos/7"
  #   cfg.vm.provider "virtualbox" do |vb|
  #     vb.name = "shoppingmallMariaDB"
  #     vb.cpus = 1
  #     vb.memory = 1024
  #   end
  #   cfg.vm.host_name = "shoppingmallMariaDB"
  #   cfg.vm.network "private_network", ip: "192.168.56.102"
  #   cfg.vm.network "forwarded_port", guest: 3306, host: 3306, auto_correct: true, id: "mardiaDB"
  #   cfg.vm.synced_folder "./mariaDB/docker", "/docker", type: 'nfs', create: true
  #   cfg.vm.provision "shell", path: "./mariaDB/install.sh"
  #
  # end

  config.vm.define "shoppingmallJenkins" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "shoppingmallJenkins"
      vb.cpus = 1
      vb.memory = 1024
    end
    cfg.vm.host_name = "shoppingmallJenkins"
    cfg.vm.network "private_network", ip: "192.168.56.103"
    cfg.vm.network "forwarded_port", guest: 9090, host: 9090, auto_correct: true, id: "jenkins"
    cfg.vm.synced_folder "./jenkins/data", "/home/vagrant/data", type: 'nfs', create: true
    cfg.vm.provision "shell", path: "./jenkins/install.sh"
  end

  config.vm.define "shoppingmallGitlab" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "shoppingmallGitlab"
      vb.cpus = 2
      vb.memory = 4096
    end
    cfg.vm.host_name = "shoppingmallGitlab"
    cfg.vm.network "private_network", ip: "192.168.56.104"
    cfg.vm.network "forwarded_port", guest: 90, host: 90, auto_correct: true, id: "gitlab"
    cfg.vm.provision "shell", path: "./gitlab/install.sh"
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
